connection_params:
  port: /dev/ttyUSB0
  dxl_baud: 115200
  
joints:
  joint_1:
    name: ang_joint1
    id: 0
    type: MX
    velocity: 5.0
    home_position: 0.0
    costrains:
      max_position: 3.14
      min_position: -3.14
