moveit:
  manipulator:
    planner: RRT
    planning_group_name: maipulator_group

  gripper:
    planner: NULL
    planning_group_name: gripper_group

services:
  manipulator_cmd_service:
    name: manipulator_cmd_service
    saved_poses:
      [
        { name: "home", vals: [0.0, 90, -90, 0.0, 0.0] },
        { name: "pack", vals: [-180.0, -21.0, -67.0, -2.0, 0.0] },
      ]
  gripper_cmd_service:
    name: gripper_cmd
    saved_poses: [{ name: "open", val: 0.025 }, { name: "close", val: 0.01 }]
