driver_settings:
  wheel_base_long:  0.265 # m
  wheel_base_width: 0.385 # m
  wheel_deameter:  0.15  # m
  
  output_data: "PWM"
  # output_data: "ANGULAR_VELOCITIES"

  max_wheel_angular_velocity: 13.0 #rad/s
  min_pwm_output: 120.0

  system:
    controller_port: "/devt/ttyACM0"
    controller_baudrate: 115200
    velocities_input_topic_name: "/cmd_vel"
    forward_left_output_topic_name: "/wheels/forward_left/target_value"
    forward_right_output_topic_name: "/wheels/forward_right/target_value"
    backward_left_output_topic_name: "/wheels/backward_left/target_value"
    backward_right_output_topic_name: "/wheels/backward_right/target_value" 
