ang_joint1:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 4095
  Moving_Speed: 40
ang_joint2:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 1023
  CCW_Angle_Limit: 3072
  Moving_Speed: 40

ang_joint3:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 1023
  CCW_Angle_Limit: 3072
  Moving_Speed: 40

ang_joint4:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 1023
  CCW_Angle_Limit: 3072
  Moving_Speed: 40

ang_joint5:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 40

ang_gripper:
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 40
