<?xml version="1.0"?>
<robot name="omnibot_platform" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_lenth" value="0.30510" />
    <xacro:property name="base_width" value="0.336" />
    <xacro:property name="base_height" value="0.200" />
    <xacro:property name="robot_mass" value="5.0" />


    <xacro:property name="wheel_mass" value="0.5" />
    <xacro:property name="wheel_deameter" value="0.15" />
    <xacro:property name="wheel_radius" value="${wheel_deameter/2}" />
    <xacro:property name="wheel_width" value="0.3" />

    <xacro:property name="wheel_x_offset" value="${(base_lenth / 2)}" />
    <xacro:property name="wheel_y_offset" value="${(base_width / 2)}" />


    <xacro:macro name="cylinder_inertia_calculator" params="*origin m r h">
        <inertial>
            <xacro:insert_block name="origin" />
            <mass value="${m}" />
            <!-- <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}" /> -->
            <!-- <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" /> -->
           <!-- <inertia ixx="1e-10" ixy="0.0" ixz="1e-10" iyy="0.0" iyz="0.0" izz="1e-10"/> -->
          <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>


    </xacro:macro>

    <xacro:macro name="box_inertia_calculator" params="*origin m x y z">
        <inertial>
            <xacro:insert_block name="origin" />
            <mass value="${m}" />
            <!-- <inertia ixx="${0.83*m*(y+z)}" ixy="0.0" ixz="0.0" iyy="${0.83*m*(x+z)}" iyz="0.0" izz="${0.83*m*(y+x)}" /> -->
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel_template" params="suffix *origin">
        <link name="${suffix}_wheel_link">
            <visual name="">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://omnibot_platform/meshes/wheel_low.dae" scale="0.001 0.001 0.001" />
                </geometry>
                <material name="">
                    <color rgba="1.0 0.0 0.0 1.0" />
                    <texture filename="" />
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://omnibot_platform/meshes/wheel_low.dae" scale="0.001 0.001 0.001" />
                </geometry>
            </collision>
<<<<<<< HEAD
            <inertial>
			    <origin xyz="0 0.0 0" rpy="0 0 0" />
			    <mass value="0.2" />
			    <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
		    </inertial>
=======
            <xacro:cylinder_inertia_calculator m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}">
                <xacro:insert_block name="origin" />
            </xacro:cylinder_inertia_calculator>
>>>>>>> 539d3a378cd48d3556f85776a1d8884e9df79ef8
        </link>

        <gazebo reference="${suffix}_wheel_link">
            <kp>10000.0</kp>
            <kd>10000.0</kd>
            <mu1>1000.0</mu1>
            <mu2>1000.0</mu2>
            <minDepth>0.001</minDepth>
            <maxVel>1.0</maxVel>
        </gazebo>

        <joint name="${suffix}_wheel_joint" type="continuous">
            <xacro:insert_block name="origin" />
            <parent link="base_link" />
            <child link="${suffix}_wheel_link" />
            <axis xyz="0.0 1.0 0.0" />
<<<<<<< HEAD
            <limit effort="0.0" velocity="0.0" />
=======
            <limit effort="5.0" velocity="100000.0" />
>>>>>>> 539d3a378cd48d3556f85776a1d8884e9df79ef8
        </joint>

        <transmission name="${suffix}_wheel_transmission" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${suffix}_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${suffix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>


    <link name="base_link">
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 3.14 0.0" />
            <geometry>
                <mesh filename="package://omnibot_platform/meshes/hodovaya_low.dae" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.5 1.0" />
                <texture filename="" />
            </material>
        </visual>
        <collision>
<<<<<<< HEAD
            <origin xyz="0.0 0.0 0.0" rpy="0.0 3.14 0.0"  />
=======
            <origin xyz="0.0 0.0 0.0" rpy="0.0 3.14 0.0" />
>>>>>>> 539d3a378cd48d3556f85776a1d8884e9df79ef8
            <geometry>
                <mesh filename="package://omnibot_platform/meshes/hodovaya_low.dae" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
<<<<<<< HEAD
        <inertial>
			<origin xyz="0 0.0 0" rpy="0 0 0" />
			<mass value="3.0" />
			<inertia ixx="1.0" ixy="1.0" ixz="1.0" iyy="0.01" iyz="0.0" izz="0.01" />
		</inertial>
=======

        <xacro:box_inertia_calculator m="${robot_mass}" x="${base_lenth}" y="${base_width}" z="${base_height}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 3.14 0.0" />
        </xacro:box_inertia_calculator>
>>>>>>> 539d3a378cd48d3556f85776a1d8884e9df79ef8
    </link>

    <xacro:wheel_template suffix="left_forward">
        <origin xyz="${-wheel_x_offset} ${wheel_y_offset} 0.013285" rpy="0.0 0.0 1.57" />
    </xacro:wheel_template>

    <xacro:wheel_template suffix="right_forward">
        <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0.013285" rpy="0.0 0.0 -1.57" />
    </xacro:wheel_template>

    <xacro:wheel_template suffix="left_backward">
        <origin xyz="${-wheel_x_offset} ${-wheel_y_offset} 0.013285" rpy="0.0 0.0  1.57" />
    </xacro:wheel_template>

    <xacro:wheel_template suffix="right_backward">
        <origin xyz="${wheel_x_offset} ${-wheel_y_offset} 0.013285" rpy="0.0 0.0  -1.57" />
    </xacro:wheel_template>

</robot>