gazebo_ros_control:
  pid_gains:
    left_front_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    right_front_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    left_back_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    right_back_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
left_front_mecanum_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_front_mecanum_joint
  pid:
    p: 10.0
    i: 1.0
    d: 0.0
right_front_mecanum_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_front_mecanum_joint
  pid:
    p: 10.0
    i: 1.0
    d: 0.0
left_back_mecanum_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_back_mecanum_joint
  pid:
    p: 10.0
    i: 1.0
    d: 0.0
right_back_mecanum_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_back_mecanum_joint
  pid:
    p: 10.0
    i: 1.0
    d: 0.0

  