
from: "/omnibot_platform/joint_control"
to:
  [
    "/omnibot_platform/left_front_mecanum_controller/command",
    "/omnibot_platform/right_front_mecanum_controller/command",
    "/omnibot_platform/left_back_mecanum_controller/command",
    "/omnibot_platform/right_back_mecanum_controller/command",
  ]
