obstacle_range: 2.0
raytrace_range: 4.0

footprint: [[-0.25, 0.25], [0.25, 0.25],[0.25, -0.25], [-0.25, -0.25]]


map_topic: /map
subscribe_to_updates: true
map_type: costmap



obstacles_layer:
  enabled: true
  combination_method: 0
  observation_sources:  scan bump
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true
    obstacle_range: 1.0
    raytrace_range: 2.0
    min_obstacle_height: 0.2
    max_obstacle_height: 2.0
  bump:
    data_type: PointCloud2
    topic: /d400/depth/color/points
    marking: true
    clearing: true
    min_obstacle_height: 0.2
    max_obstacle_height: 2.0

    
  # for debugging only, let's you see the entire voxel grid

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.3  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  
recovery_behaviors:
- {'name': 'conservative_reset', 'type': 'clear_costmap_recovery/ClearCostmapRecovery'}
- {'name': 'aggressive_reset', 'type': 'clear_costmap_recovery/ClearCostmapRecovery'}