obstacle_range: 2.0
raytrace_range: 4.0

footprint: [[-0.25, 0.25], [0.25, 0.25],[0.25, -0.25], [-0.25, -0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

map_topic: /rtabmap/grid_map
subscribe_to_updates: true


observation_sources: point_cloud_sensor

point_cloud_sensor: {
  sensor_frame: d400_link,
  data_type: PointCloud2, 
  topic: /d400/depth/color/points,
  marking: true, 
  clearing: true}

obstacle_layer:
  enabled:              true
  max_obstacle_height:  10.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             2
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 1.2
  raytrace_range: 5.0
  publish_voxel_map: true
  observation_sources:  scan
  scan:
    data_type: PointCloud2
    topic: rtabmap/cloud_obstacles
    sensor_frame: d400_link
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 5.0

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0
  inflation_radius:     0.5 # 0.36 

static_layer:
  enabled:              true