costmap_converter/CostmapToPolygonsDBSMCCH:
# costmap_converter/CostmapToLinesDBSRANSAC:
# costmap_converter/CostmapToLinesDBSMCCH:
# costmap_converter/CostmapToPolygonsDBSConcaveHull:
  cluster_max_distance: 0.4
  cluster_min_pts: 2
  ransac_inlier_distance: 0.15
  ransac_min_inliers: 10
  ransac_no_iterations: 2000
  ransac_remainig_outliers: 3
  ransac_convert_outlier_pts: True
  ransac_filter_remaining_outlier_pts: False
  convex_hull_min_pt_separation: 0.1
