obstacle_range: 1.0
raytrace_range: 3.0

footprint: [[-0.25, 0.25], [0.25, 0.25],[0.25, -0.25], [-0.25, -0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.4

map_topic: /rtabmap/grid_map
subscribe_to_updates: true

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: d400_link, data_type: PointCloud2, topic: /d400/depth/color/points, marking: true, clearing: true}