TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.5
 dt_hysteresis: 0.1
 max_samples: 500
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 3.0
 global_plan_viapoint_sep: 1
 global_plan_prune_distance: 1
 exact_arc_length: False
 feasibility_check_no_poses: 5
 publish_feedback: True
    
 # Robot
         
 max_vel_x: 3.0
 max_vel_x_backwards: 0.3
 max_vel_y: 3.0
 max_vel_theta: 2.0
 acc_lim_x: 0.5
 acc_lim_y: 0.5
 acc_lim_theta: 0.5
 min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
 footprint_model:
   type: "polygon"
   vertices: [[-0.25, 0.25], [0.25, 0.25], [0.25, -0.25], [-0.25, -0.25]]

 # GoalTolerance
    
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.7
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 inflation_dist: 0.35
 obstacle_poses_affected: 30
#  costmap_converter_plugin:  "costmap_converter::CostmapToPolygonsDBSMCCH"
 #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
 costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
#  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
#  costmap_converter_plugin: "" # deactivate plugin
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5



 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.01
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: True
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: True

