joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
# joint_velocity_controller:
#     type: JointVelocityController
#     publish_rate: 50

gazebo_ros_control:
  pid_gains:
    left_forward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    right_forward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    left_backward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    right_backward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0