joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
<<<<<<< HEAD
=======
    
# joint_velocity_controller:
#     type: JointVelocityController
#     publish_rate: 50

>>>>>>> 539d3a378cd48d3556f85776a1d8884e9df79ef8
gazebo_ros_control:
  pid_gains:
    left_forward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    right_forward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    left_backward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    right_backward_wheel_joint:
      p: 100.0
      i: 0.01
      d: 10.0