io:
  manipulator: action_name
omnibot_manipulator:
  moveit:
    manipulator:
      planning_group_name: maipulator_group
      home: [0.0, 90.0, -90.0, 0, 0] # J1 J2 J3 J4 J5
    gripper:
      planning_group_name: gripper_group
      home: 0.0

    logname: omnibot_manipulator_log

visual:
  link: ang_link0
