gazebo_ros_control:
  pid_gains:
    left_front_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    right_front_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    left_back_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0
    right_back_mecanum_joint:
      p: 10.0
      i: 1.0
      d: 0.0