gazebo_ros_control:
  pid_gains:
    left_front_omniwheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_front_omniwheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    left_back_omniwheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_back_omniwheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0