# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: angle_manip
  joint_model_group_pose: start_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ang_joint1
    - ang_joint2
    - ang_joint3
    - ang_joint4
    - ang_joint5
    - ang_gripper
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []
  - name: angle_manip_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ang_joint1
      - ang_joint2
      - ang_joint3
      - ang_joint4
      - ang_joint5