controller_list:
  - name: fake_maipulator_group_controller
    type: $(arg fake_execution_type)
    joints:
      - ang_joint1
      - ang_joint2
      - ang_joint3
      - ang_joint4
      - ang_joint5
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - ang_gripper
initial:  # Define initial robot poses per group
  - group: maipulator_group
    pose: pack_pose