maipulator_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ang_joint1
    - ang_joint2
    - ang_joint3
    - ang_joint4
    - ang_joint5
  gains:
    ang_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ang_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ang_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ang_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ang_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ang_gripper
  gains:
    ang_gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1