# Params for the octomap monitor
octomap_frame: d400_link


sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /rtabmap/cloud_map
    # point_cloud_topic: /rtabmap/cloud_obstacles
    # point_cloud_topic: /local_grid_obstacle
    max_range: 10.0
    max_update_rate: 0.5
    point_subsample: 1
    padding_offset: 0.25
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
