# Params for the octomap monitor



sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    # point_cloud_topic: /rtabmap/cloud_map
    # point_cloud_topic: /rtabmap/cloud_obstacles
    point_cloud_topic: /rtabmap/local_grid_obstacle
    # point_cloud_topic: /d400/depth/color/points
    max_range: 2.0
    max_update_rate: 100.0
    point_subsample: 1
    padding_offset: 0.5
    padding_scale: 2.0
    filtered_cloud_topic: filtered_cloud
