sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /cloud_map
    # point_cloud_topic: /local_grid_obstacle
    max_range: 10.0
    max_update_rate: 0.05
    point_subsample: 1
    padding_offset: 0.25
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
  # - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   image_topic: /d400/aligned_depth_to_color/image_raw
  #   queue_size: 5
  #   near_clipping_plane_distance: 0.3
  #   far_clipping_plane_distance: 5.0
  #   shadow_threshold: 0.2
  #   padding_scale: 4.0
  #   padding_offset: 0.03
  #   max_update_rate: 0.05
  #   filtered_cloud_topic: filtered_cloud
  #   ns: d400