controller_list:
  - name: /maipulator_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ang_joint1
      - ang_joint2
      - ang_joint3
      - ang_joint4
      - ang_joint5
  - name: /gripper_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ang_gripper