cubes: [
  {cube_name: cube_0, cube_pos:   [1.15,-2.5, 0.3],  cube_ori: [0.0,0.0,0.0]},
  {cube_name: cube_1, cube_pos:   [1.15,-2.7, 0.3],  cube_ori: [0.0,0.0,0.0]},
  {cube_name: cube_2, cube_pos:   [1.15,-2.3, 0.3],  cube_ori: [0.0,0.0,0.0]},
  {cube_name: cube_3, cube_pos:   [1.15,-2.9, 0.3],  cube_ori: [0.0,0.0,0.0]},
  {cube_name: cube_4, cube_pos:   [1.15,-2.1, 0.3],  cube_ori: [0.0,0.0,0.0]},
  {cube_name: cube_5, cube_pos:   [0.04,4.6, 0.08],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_6, cube_pos:   [0.34,4.6, 0.08],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_7, cube_pos:   [-0.24,4.6,0.08],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_8, cube_pos:   [0.04,4.6, 0.45],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_9, cube_pos:   [0.34,4.6, 0.45],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_10, cube_pos:  [-0.24,4.6,0.45],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_11, cube_pos:  [1.04,4.6, 0.08],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_12, cube_pos:  [1.34,4.6, 0.08],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_13, cube_pos:  [0.74,4.6,0.08],   cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_14, cube_pos:  [1.04,4.6, 0.45],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_15, cube_pos:  [1.34,4.6, 0.45],  cube_ori: [1.1,0.0,0.0]},
  {cube_name: cube_16, cube_pos:  [0.74,4.6,0.45],   cube_ori: [1.1,0.0,0.0]},
  # {cube_name: cube_17, cube_pos: [0.0,0.0,0.0],cube_ori: [0.0,0.0,0.0]},
  # {cube_name: cube_18, cube_pos: [0.0,0.0,0.0],cube_ori: [0.0,0.0,0.0]},
  # {cube_name: cube_19, cube_pos: [0.0,0.0,0.0],cube_ori: [0.0,0.0,0.0]},
  # {cube_name: cube_20, cube_pos: [0.0,0.0,0.0],cube_ori: [0.0,0.0,0.0]},
]