input_topic: "/cmd_vel"
output_topic: "/joint_control"
output_topic_frame_id: "/joint_control"
output_topic_rate: 40.0

wheels_joints_count: 4

wheels_joints_names:
  [
    "left_front_mecanum_joint", "right_front_mecanum_joint", "left_back_mecanum_joint",  "right_back_mecanum_joint"
  ]

wheels_joints_reverse:
  [
    false, false,false, false
  ]

wheels_deameter: 0.15
wheels_width:    0.3
wheels_max_velocity: 100.0

wheel_base_width: 0.306100
wheel_base_lenth: 0.336000

velocities_limits:
  linear_x_max:   1.0
  linear_x_min:  -1.0

  linear_y_max:   1.0
  linear_y_min:  -1.0

  angular_z_max:  2.0
  angular_z_min: -2.0


pid_gains:
    left_front_mecanum_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_front_mecanum_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    left_back_mecanum_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_back_mecanum_joint:
      p: 1.0
      i: 0.0
      d: 0.0