<?xml version="1.0"?>
<robot name="omnibot_platform" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_lenth" value="0.30510" />
    <xacro:property name="base_width" value="0.336" />
    <xacro:property name="base_height" value="0.15" />

    <xacro:property name="wheel_x_offset" value="${(base_lenth / 2)}" />
    <xacro:property name="wheel_y_offset" value="${(base_width / 2)}" />

    <!-- wheel template -->
    <xacro:macro name="wheel_template" params="suffix *origin">
        <link name="${suffix}_wheel_link">
            <visual name="">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://omnibot_platform/meshes/wheel.STL" scale="0.001 0.001 0.001" />
                </geometry>
                <material name="">
                    <color rgba="1.0 0.0 0.0 1.0" />
                    <texture filename="" />
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://omnibot_platform/meshes/wheel.STL" scale="0.001 0.001 0.001" />
                </geometry>
            </collision>
        </link>

        <joint name="${suffix}_wheel_joint" type="continuous">
            <xacro:insert_block name="origin" />
            <parent link="base_link" />
            <child link="${suffix}_wheel_link" />
            <axis xyz="0.0 0.0 1.0" />
            <limit effort="0.0" velocity="0.0" />
        </joint>

        <transmission name="${suffix}_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${suffix}_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${suffix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>
    <!-- #######################################################################################################333333333 -->

    <link name="base_link">
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 3.14" />
            <geometry>
                <mesh filename="package://omnibot_platform/meshes/base.STL" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.5 1.0" />
                <texture filename="" />
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <mesh filename="package://omnibot_platform/meshes/base.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
    </link>
    
    <xacro:wheel_template suffix="left_forward">
        <origin xyz="${-wheel_x_offset} ${wheel_y_offset} 0.013285" rpy="0.0 1.57 0.0" />
    </xacro:wheel_template>

    <xacro:wheel_template suffix="right_forward">
        <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0.013285" rpy="0.0 -1.57 0.0" />
    </xacro:wheel_template>

    <xacro:wheel_template suffix="left_backward">
        <origin xyz="${-wheel_x_offset} ${-wheel_y_offset} 0.013285" rpy="0.0 1.57 0.0" />
    </xacro:wheel_template>

    <xacro:wheel_template suffix="right_backward">
        <origin xyz="${wheel_x_offset} ${-wheel_y_offset} 0.013285" rpy="0.0 -1.57 0.0" />
    </xacro:wheel_template>

</robot>